routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','Site\Home\indexController@index');
Route::get('/verify-code/{email}','Site\Home\indexController@verifyCode')->name('verify-code');
Route::post('/verify-code/{email}','Site\Home\indexController@verifyAccount')->name('verifyAccount');
Route::get('/categories/{category_name}/{category_id}/{sub_cat_id?}','Site\Home\ProductsController@index')->name('products');
Route::post('/Cart/{product_id}','Site\Home\ProductsController@addToCart')->name('addToCart');
Route::get('/ProductDetails/{product}','Site\Home\ProductsController@view')->name('show-product');
Route::get('/sub_category/{sub_cat_id}','Site\Home\ProductsController@filter')->name('filter');
Route::post('/login', 'Site\Home\indexController@login')->name('login');
Route::get('/cart','Site\Home\CartController@index')->name('viewCart');
Route::get('/remove_from_cart/{cart_id}','Site\Home\CartController@destroy')->name('remove_from_cart');
Route::get('/add_event','Site\Home\ProductsController@add_event')->name('add_event');
Route::post('/getCategories', 'Site\Home\ProductsController@getCategories');
Route::post('/product/save', 'Site\Home\ProductsController@saveProduct')->name('product.save');
Route::get('/myproducts','Site\Home\ProfileController@index')->name('myproducts');
Route::get('/product/{id}/edit','Site\Home\ProductsController@saveProduct')->name('edit-product');
Route::Delete('/product/{id}/destroy','Site\Home\ProductsController@destroy')->name('destroy-product');
Route::get('/Product/{id}/edit','Site\Home\ProductsController@edit')->name('product.edit');
Route::patch('/Product/{id}/update','Site\Home\ProductsController@update')->name('product.update');
Route::get('/Productrate/{rate}/{product_id}','Site\Home\ProductsController@rate')->name('rate');






// Route::post('/subcat', function () {

//     $cat_id = $request->cat_id;
//     // dd($cat_id);
//     $subcategories = SubCategory::where('category_id',$cat_id)->get();

//     return response()->json([
//         $subcategories
//     ]);

// })->name('subcat');


// route::get('/products/{product}','Site\Home\ProductsController@view')->name('view_product');
// route::get('/viewproduct/{id}','ProductDetailsController@index')->name('viewproduct');
// Route::post('/sort','Site\Home\ProductsController@sort')->name('sort-category');
Auth::routes();

Route::prefix('admin')->group(function() {
    Route::get('/','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.dashboard');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/users','Admin\UsersController@index')->name('view-users');
    Route::delete('/users/{id}','Admin\UsersController@destroy')->name('admin-destroy-users');
    Route::get('/users/{id}/contact','Admin\UsersController@Contact')->name('admin-contact-users');
    Route::post('/users/{user}','Admin\UsersController@store')->name('admin-store-users');
    Route::get('/admins/create','Admin\AdminController@create')->name('create-admin');
    Route::post('/admins/store','Admin\AdminController@store')->name('store-admin');
    Route::get('/admins','Admin\AdminController@index')->name('view-admins');
    Route::delete('/admins/{id}','Admin\AdminController@destroy')->name('admin-destroy-admins');
    ////////////////////////////////////////////////////////
    Route::get('/categories','Admin\CategoryController@index')->name('view-categories');
    Route::get('/categories/create','Admin\CategoryController@create')->name('create-category');
    Route::post('/categories','Admin\CategoryController@store')->name('store-category');
    Route::get('/categories/{category}','Admin\CategoryController@show')->name('admin-show-category');
    Route::get('/categories/{category_name}/Sub-category/{id}','Admin\SubCategoryController@show')->name('admin-show-subCategory');
    Route::get('/categories/{category}/edit','Admin\CategoryController@edit')->name('admin-edit-category');
    Route::patch('/categories/{category}','Admin\CategoryController@update')->name('admin-update-category');
    Route::delete('/categories/{id}','Admin\CategoryController@destroy')->name('admin-destroy-category');
    Route::delete('/categories/{id}/delete','Admin\SubCategoryController@destroy')->name('admin-destroy-SubCategory');
    Route::get('/categories/{category}/create-sub-cat','Admin\SubCategoryController@create')->name('admin-create-sub-category');
    Route::post('/categories/{category}','Admin\SubCategoryController@store')->name('admin-store-sub-category');
    Route::get('/categories/{category_id}/SubCategory-{Subcategory}/edit','Admin\SubCategoryController@edit')->name('admin-edit-sub_category');
    Route::patch('/subcategories/{Subcategory}','Admin\SubCategoryController@update')->name('admin-update-subcategory');
    /////////////////////////////////////////////////////////
    Route::get('/countries/create','Admin\CountryController@create')->name('admin-create-country');
    Route::post('/countries','Admin\CountryController@store')->name('admin-store-country');
    Route::get('/countries','Admin\CountryController@index')->name('view-countries');
    Route::get('/countries/{country}','Admin\CountryController@show')->name('admin-show-country');
    Route::get('/countries/{country}/edit','Admin\CountryController@edit')->name('admin-edit-country');
    Route::patch('/countries/{country}','Admin\CountryController@update')->name('admin-update-country');
    Route::delete('/countries/{id}/delete','Admin\CountryController@destroy')->name('admin-destroy-country');
    Route::get('/countries/{country}/create-city','Admin\CityController@create')->name('admin-create-city');
    Route::post('/countries/{country}','Admin\CityController@store')->name('admin-store-city');
    Route::delete('/countries/{id}','Admin\CityController@destroy')->name('admin-destroy-city');

    ////////////////////////////////////////////////////////
    Route::get('/products','Admin\ProductsController@index')->name('admin-view-products');
    Route::get('/products/{product}','Admin\ProductsController@show')->name('admin-view-product_details');
    Route::post('/products/{product}','Admin\ProductsController@accept')->name('admin-accept-products');
    Route::post('/products/{id}/hold','Admin\ProductsController@hold')->name('admin-hold-products');
    Route::delete('/products/{product}','Admin\ProductsController@destroy')->name('admin-destroy-product');
    ///////////////////////////////////////////////////////////
    Route::get('/banners','Admin\BannersController@index')->name('admin-view-banners');
    Route::get('/banners/create','Admin\BannersController@create')->name('admin-add-banner');
    Route::post('/banners/store','Admin\BannersController@store')->name('admin-store-banner');
    Route::delete('/banners/{id}','Admin\BannersController@destroy')->name('admin-destroy-banner');

}) ;

app/Category.php
<?php

namespace App;
use App\SubCategory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['category_name', 'category_name_ar','category_image'];

    public function getSiteNameAttribute()
    {
        if (app()->getLocale() == "en")
            return $this->category_name;
        else
            return $this->category_name_ar;
    }


    public function subcategory(){
        return $this->hasMany(SubCategory::class);
    }
    public function products(){
        return $this->hasMany('App\Products','cat_id');
    }
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Category;
use App\Country;
use App\Products;
use App\User;
use App\Banners;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(){
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $categories = Category::take(5)->get();
        $products = Products::take(5)->get();
        $countries = Country::take(5)->get();
        $users        = User::take(5)->get();
        $banners = Banners::take(5)->get();

        return view('Admins.dashboard-home',compact('categories','products','countries','users','banners'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Site/Home/CartController.php
<?php
namespace App\Http\Controllers\Site\Home;
use App\Http\Controllers\Controller;
use App\Products;
use App\SubCategory;
use App\Category;
use App\City;
use App\Cart;
use App\User;
use Illuminate\Http\Request;
use Validator;
use DB;
use Auth;
use Session;

class CartController extends Controller
{
    public function __construct(){

        $this->middleware('auth');
        // $this->middleware('guest:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $total_price = 0 ;
        $user_id = Auth::User()->id;
        $cart = Cart::where('user_id',$user_id)->get();
        $cart_items = DB::table('carts')
                    ->join('products','carts.product_id' , '=' , 'products.product_id')
                    ->select('products.product_id','carts.quantity','carts.days_num','carts.start_date','carts.end_date','products.name','products.image','products.price','products.status')->where('carts.order_id',null)->get();
        foreach($cart_items as $cart_item){
            $Splitted1 =  preg_split('#(?<=\d)()(?=[a-z])#i', $cart_item->price);
            $Splitted2 =  explode(" ",$Splitted1[0]);
            $cart_item->total_pricePerItem = $Splitted2[0] * $cart_item->days_num * $cart_item->quantity ;


            $product_img_array = explode('|', $cart_item->image);
            $cart_item->image =$product_img_array[0];
        }
        for($i = 0 ; $i < count($cart_items) ; $i++ ){
            $total_price = $total_price + $cart_items[$i]->total_pricePerItem;
        }

        return view('site.home.cart',compact('cart_items','total_price'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public  function show(Cart $cart)
    {
        $rules = [
            'useri_d'=>'required|numeric|exists:users,id',
            'api_token'=>'required'
        ];
        $items = array();
        $validator = Validator::make(request()->all(),$rules);
        if($validator->fails()){
            result(401,$validator->messages(),null);
        }
        if(CartController::isLogin(request('api_token'),request('user_id')) == true){
            $userCart = Cart::where('user_id',request('user_id'))->where('billing_status',null)->get();
            if(!empty($userCart)){
                foreach($userCart as $cart){
                    $item = Products::select('product_id','name','price','image')->where('product_id',$cart->product_id)->first();
                    $item_datailes = (object)[
                        'cart_id'=>$cart->id,
                        'quantity'=>$cart->quantity,
                        'product_id'=>$item->product_id,
                        'product_name'=>$item->name,
                        'product_price'=>$item->price,
                        'product_image'=>"http://www.vretech.com/images/products/".$item->image
                    ];
                    array_push($items,$item_datailes);
                }
                if(!empty($items)){
                    result(200,'Success request',$items);
                }else{
                    result(401,'User has No items in cart',null);
                }
            }
            else{
                result(401,'User has No items in cart',null);
            }
        }else{
            result(401,'Please Login first',null);
        }

    }


    public static function isLogin(){

        if(Auth::check())
        {
            return true;
        }
        else{
            return false;
        }

    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function edit(Cart $cart)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cart $cart)
    {
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function destroy($cart_id)
    {
            if(CartController::isLogin() == true){
                    Cart::where('product_id',(int)$cart_id)->where('billing_status',null)->where('user_id',Auth::User()->id)->delete();
                    return back();
        }
    }
}

app/Http/Controllers/Site/Home/ProfileController.php
<?php
namespace App\Http\Controllers\Site\Home;
use App\Http\Controllers\Controller;
use App\Products;
use App\SubCategory;
use App\Category;
use App\City;
use App\Cart;
use App\User;
use Illuminate\Http\Request;
use Validator;
use DB;
use Auth;
use Session;

class ProfileController extends Controller
{
    public function __construct(){

        $this->middleware('auth');
        // $this->middleware('guest:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

            $products = Products::where('owner_id',Auth::user()->id)->paginate(15);



        foreach($products as $product){
            $product_img_array = explode('|', $product->image);
            $product->image =$product_img_array[0];
        }

            return view('site.home.UserProducts',compact('products'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public  function show(User $user)
    {


    }


    public static function isLogin(){
        if(Auth::check())
        {
            return true;
        }
        else{
            return false;
        }
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request )
    {
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {

    }
}

resources/views/site/home/Add_event.blade.php
@extends('site.layout.container')
@section('content')
@if (Session::has('error'))
   <div class="alert alert-danger text-center">{{ Session::get('error') }}</div>
   @elseif(Session::has('success'))
    <div class="alert alert-success text-center">{{ Session::get('success') }}</div>
@endif

<div class="container">
    <form action="{{ route('product.save') }}"method="POST" enctype="multipart/form-data" class="col-lg-12">
        @csrf
        <div class="row" >
            @include('site.home.form')
        </div>
        <input type="submit" class="btn btn-success" value="{{trans('language.submit')}}">
    </form>
</div>
@endsection

resources/views/site/home/UserProducts.blade.php
@extends('site.layout.container')
@section('content')
<div class="main-content ">
    <div class="container">
        <div class="col-md-12 col-lg-12">
    <div class="row">
@foreach ($products as $product )
            <div class="col-md-6 col-lg-3 ">
                <div class="product all ">
                        <span class="product-image">
                        <img src="{{ url('images/products/'.$product->image) }}" alt="Image" class="img-fluid">
                        </span>
                        <a href="{{route('show-product', $product->product_id)}}">
                            <span class="product-title">{{ $product->name }}</span>
                        </a>
                        <span class="price">{{ $product->price }}</span>
                        <div class="product-icon">
                        <ul class="global-list">
                        </ul>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
</div>

@endsection

resources/views/site/home/form.blade.php
        <div class="form-group col-lg-12">
            <div class="form-group col-lg-12"style="display: inline-block; padding-right:30px;">
                <label for="product_name">{{trans('language.productname')}}</label>
                <input type="text" class="form-control" id="product_name" name ="product_name" aria-describedby="product_name" placeholder="{{trans('language.productname')}}" required>
                <div>{{ $errors->first('product_name') }}</div>
            </div>

            <div class="form-group col-lg-12"style="display: inline-block; padding-right:30px;">
                <label for="price">{{trans('language.price')}}</label>
                <input type="text" class="form-control" id="price" name ="price" aria-describedby="price" placeholder=" {{trans('language.price')}} $" required>
                <div>{{ $errors->first('price') }}</div>
            </div>

            <div class="form-group col-lg-12" style="display: inline-block; padding-right:30px;" required>
                <label for="category_name">{{trans('language.category')}}</label>
                <select  class="form-control main_category_id_list main_category_id"  id="main_category_id" name="main_category_id" required="required">
                    <option value="0">{{trans('language.category')}}</option>
                    @foreach(\App\Category::get() as $category)
                        <option  name="main_category_id"  value="{{$category->id}}">{{$category->site_name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group category_List col-lg-12" style="display: inline-block; padding-right:30px;">
                <label for="category_name">{{trans('language.subcategory')}}</label>
                <select  id="category_id"  name="category_id"
                         class=" form-control category_id_list category_id" required>
                    <option name="category_id" class="basicOption" value="0">{{trans('language.subcategory')}}</option>
                </select>
            </div>


            <div class="form-group col-lg-12" style="display: inline-block; padding-right:30px;">
                <label for="category_name">{{trans('language.status')}}</label>
                <select  id="status" name="status"
                         class=" form-control" required>
                    <option name="status"  value="0" disabled>{{trans('language.status')}}</option>
                    <option name="status"  value="new" >New</option>
                    <option name="status"  value="old" >Old</option>
                </select>
            </div>
            <div class="form-group col-lg-12"style="display: inline-block; padding-right:30px;" >
                <label for="description">{{trans('language.description')}}</label>
                <textarea type="text" class="form-control" id="description" name ="description" aria-describedby="description" placeholder="{{trans('language.description')}}" required></textarea>
                <div>{{ $errors->first('description') }}</div>
            </div>
            <div class="form-group col-lg-6"style="display: inline-block;"required>
                <label for="avail-qty">{{trans('language.availablequantity')}}</label>
                <input type="number" min="0"pattern="[0-9]" class="form-control" id="avail-qty" name ="avail-qty" aria-describedby="avail-qty" placeholder="{{trans('language.availablequantity')}}">
                <div>{{ $errors->first('location') }}</div>
            </div>

            <div class="form-group col-lg-6"style="display: inline-block; ">
                <label>{{trans('language.date')}}</label>
            <input type="date" name = "available_date" class="form-control" required>
            </div>

            <div class="form-group col-lg-6"style="display: inline-block;">
                <label for="avail-qty">{{trans('language.newavailablequantity')}}</label>
                <input type="number" min="0"pattern="[0-9]" class="form-control" id="new-avail-qty" name ="new-avail-qty" aria-describedby="new-avail-qty" placeholder=" {{trans('language.newavailablequantity')}}">
                <div>{{ $errors->first('location') }}</div>
            </div>
            <div class="form-group col-lg-12"style="display: inline-block; padding-right:30px;" >
                <label for="location">{{trans('language.location')}}</label>
                <input type="text" class="form-control" id="location" name ="location" aria-describedby="location" placeholder=" {{trans('language.location')}}"required>
                <div>{{ $errors->first('location') }}</div>
            </div>
            <div class="form-group">
                <label for="image">{{trans('language.image')}}</label>
                <input type="file" name="image[]" value = "" id="image" multiple>
            </div>
            @csrf
        </div>



<script>

    $(document).ready(function () {
        $('.main_category_id').on('change', function () {
            var main_category_id = $('.main_category_id').val();
            $.post("{{url("/getCategories")}}",
                {
                    category_id: main_category_id,
                    _token: "{{csrf_token()}}"
                },
                function (data, status) {
                    if (data.status == true) {
                        $('.category_id_list').html('');
                        $.each(data, function () {
                            $.each(this, function (index, item) {
                                $(".category_id_list").prepend('' +
                                    '<option name="category_id"  value="' + item.id + '">' + item.subcategory_name + '</option>');
                            });
                        });
                        // first edit is here that the following option will be showen at the top of list
                        $(".category_id_list").prepend('' +
                            '<option  value="0" disabled> Select sub category</option>');
                    } else {
                        $('.category_id_list').html('');
                        $('.category_id').empty();
                        $(".category_id_list").prepend('' +
                            '<option name="category_id"  value="0">No sub categories yet </option>');
                    }
                });
        });
    });
</script>

resources/views/site/home/index.blade.php
@extends('site.layout.container')
@section('content')

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{{asset("/assets/site")}}/images/slider_bg.jpg" alt="First slide">
                <div class="carousel-caption  d-md-block">
                    <div class="banner-info">
                        <h1 data-animation="animated fadeInDown">{{trans('language.welcometovrtech')}}</h1>
                        <h2 data-animation="animated fadeInDown">{{trans('language.buildevent')}}</h2>
                        <p data-animation="animated fadeInDown">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{{asset("/assets/site")}}/images/slider_bg.jpg" alt="Second slide">
                <div class="carousel-caption  d-md-block">
                    <div class="banner-info">
                        <h1 data-animation="animated fadeInDown">{{trans('language.welcometovrtech')}}</h1>
                        <h2 data-animation="animated fadeInDown">{{trans('language.buildevent')}}</h2>
                        <p data-animation="animated fadeInDown">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{{asset("/assets/site")}}/images/slider_bg.jpg" alt="Third slide">
                <div class="carousel-caption  d-md-block">
                    <div class="banner-info">
                        <h1 data-animation="animated fadeInDown">{{trans('language.welcometovrtech')}}</h1>
                        <h2 data-animation="animated fadeInDown">{{trans('language.buildevent')}}</h2>
                        <p data-animation="animated fadeInDown">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

    </div>

    <div class="tr-farmfood farmfood-two section-padding bg-image" style="background-image: url(images/bg/farmfood.jpg);">
        <div class="container">
            <div class="section-title">
                <h1>{{trans('language.hereweare')}}</h1>
                <h2>{{trans('language.fullservice')}}</h2>
            </div>
            <div class="row">
                @foreach($categories as $category)
                    <div class="col-md-6 col-lg-3">
                        <div class="farmfood">
                            <a href="{{ route('products',['category_name' => $category->category_name , 'category_id' => $category->id ]) }}">
                                <div class="icon">

                                    <img class="img" src={{ url('images/categories/'.$category->category_image) }} style = "width:120px;height:120px;">
                                </div>
                                <div class="food-info">
                                    <h3> <span>{{ $category->site_name }}</span></h3>
                                </div>
                            </a>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>


@endsection